name: CI Pipeline

on:
  push:
    branches: [dev]  # Trigger only on pushes to dev
permissions:
  contents: write
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run Jest tests
        run: npm test
  
  merge-to-main:
    needs: test  # Runs only if tests pass
    if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for merging

      - name: Setup Git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge dev → main
        run: |
          git fetch origin main
          git checkout main
          git merge --no-ff origin/dev -m "Auto-merge: dev → main after passing tests [skip ci]"
          git push origin main
